version: '3'

services:
  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ Management Plugin port
    environment:
      - RABBITMQ_DEFAULT_USER=username
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - paybox-network

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"  # MongoDB default port
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    volumes:
      - mongodb-data:/data/db
    networks:
      - paybox-network

networks:
  paybox-network:
    driver: bridge

volumes:
  mongodb-data: